apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-app
spec:
  selector:
    matchLabels:
      app: first-app
  replicas: 2
  template:
    metadata:
      labels:
        app: first-app
    spec:
      containers:
      - name: first-app
        image: matheuscarino/simple-python-flask-webapp
        ports:
        - containerPort: 5000